(()=>{'use strict';
const FILES={resp_003:'./diagram-resp003.b64',resp_013:'./diagram-resp013.b64',resp_015:'./diagram-resp015.b64'};
const ADD=[{"id":"resp_003","ue":"S1 B1","course":"Système respiratoire","theme":"Anatomie et voies aériennes","number":3,"question":"Sur le schéma des voies respiratoires, quelles associations sont correctes ?","choices":["E = poumon gauche.","A = cavité nasale.","D = larynx.","C = trachée.","B = pharynx."],"answers":[1,4],"explanation":"Sur le schéma, A correspond à la cavité nasale et B au pharynx. Le repère C pointe le larynx, D la trachée et E le poumon droit : les formulations C, D et E proposées sont donc fausses."},{"id":"resp_013","ue":"S1 B1","course":"Système respiratoire","theme":"Bronchioles, alvéoles et poumons","number":13,"question":"Sur le schéma de l’arbre bronchique, quelles associations sont correctes ?","choices":["B = bronchioles.","E = cartilage trachéal.","A = trachée.","D = bronches souches.","C = bronches lobaires."],"answers":[2,4],"explanation":"Sur le schéma, A désigne la trachée et C les bronches lobaires. B correspond aux bronches souches, D à une bronchiole et E au territoire alvéolaire."},{"id":"resp_015","ue":"S1 B1","course":"Système respiratoire","theme":"Bronchioles, alvéoles et poumons","number":15,"question":"Sur le schéma alvéolaire, quelles associations sont correctes ?","choices":["A = pneumocyte de type II.","D = pneumocyte de type I.","C = veine pulmonaire.","E = cellule caliciforme.","B = trachée."],"answers":[0,1],"explanation":"Sur le schéma, A correspond au pneumocyte de type II et D au pneumocyte de type I. B repère la membrane alvéolo-capillaire, C le capillaire pulmonaire et E le macrophage alvéolaire."}];
const IMG={};let added=false,patched=false,testStarted=false;
function addStyles(){if(document.getElementById('diagramCss'))return;const s=document.createElement('style');s.id='diagramCss';s.textContent='.diagram-card{margin:12px 0 14px;padding:10px;border:1px solid #e6e0ef;border-radius:16px;background:#fff;text-align:center}.diagram-card img{display:block;max-width:100%;max-height:460px;margin:auto;border-radius:10px;cursor:zoom-in}.diagram-hint{margin-top:7px;color:#6c6878;font-size:12px}.diagram-modal{position:fixed;inset:0;z-index:9999;background:rgba(18,16,28,.92);display:flex;align-items:center;justify-content:center;padding:18px}.diagram-modal.hidden{display:none!important}.diagram-modal img{max-width:96vw;max-height:90vh;object-fit:contain;border-radius:12px;background:#fff;box-shadow:0 18px 60px #0008}.diagram-close{position:fixed;top:18px;right:18px;border:0;border-radius:999px;background:#fff;color:#242332;width:44px;height:44px;font-size:24px;font-weight:900;cursor:pointer}';document.head.appendChild(s)}
function ensureModal(){if(document.getElementById('diagramModal'))return;const m=document.createElement('div');m.id='diagramModal';m.className='diagram-modal hidden';m.innerHTML='<button class="diagram-close" aria-label="Fermer">×</button><img alt="Schéma agrandi">';m.onclick=e=>{if(e.target===m||e.target.classList.contains('diagram-close'))m.classList.add('hidden')};document.body.appendChild(m);document.addEventListener('keydown',e=>{if(e.key==='Escape')m.classList.add('hidden')})}
async function loadImages(){for(const [id,url] of Object.entries(FILES)){try{const r=await fetch(url);if(r.ok)IMG[id]='data:image/webp;base64,'+(await r.text()).trim()}catch(e){console.warn('Schéma absent',id)}}}
function zoom(src){const m=document.getElementById('diagramModal');if(!m)return;m.querySelector('img').src=src;m.classList.remove('hidden')}
function renderDiagram(){document.getElementById('diagramCurrent')?.remove();let q;try{q=session&&session[i]}catch{};if(!q||!IMG[q.id])return;const box=document.createElement('div');box.id='diagramCurrent';box.className='diagram-card';box.innerHTML='<img src="'+IMG[q.id]+'" alt="Schéma de la question"><div class="diagram-hint">🔎 Toucher / cliquer sur le schéma pour l’agrandir</div>';box.querySelector('img').onclick=()=>zoom(IMG[q.id]);const choices=document.getElementById('choices');choices?.parentNode?.insertBefore(box,choices)}
function addQuestions(){if(added||!Array.isArray(Q)||!Q.length)return false;const ids=new Set(Q.map(q=>q.id));for(const q of ADD)if(!ids.has(q.id))Q.push(q);added=true;try{fill()}catch(e){}return true}
function patchDraw(){if(patched)return;try{const prev=draw;draw=function(){prev();renderDiagram()};patched=true}catch(e){}}
function maybeStartTest(){if(testStarted||!added||!patched)return;const p=new URLSearchParams(location.search);if(p.get('testschema')!=='1')return;const ids=new Set(ADD.map(q=>q.id));const testQ=Q.filter(q=>ids.has(q.id)).sort((a,b)=>a.number-b.number);if(testQ.length){testStarted=true;begin(testQ)}}
addStyles();ensureModal();loadImages();let tries=0;const t=setInterval(()=>{tries++;if(addQuestions())patchDraw();if(added&&patched){maybeStartTest();if(testStarted||!(new URLSearchParams(location.search).get('testschema')==='1'))clearInterval(t);const u=document.getElementById('update');if(u)u.textContent='Application prête • test schémas actif sur 3 questions respiratoires.'}if(tries>120)clearInterval(t)},125);
})();