(()=>{
'use strict';
if(new URLSearchParams(location.search).get('tnr')!=='1')return;
const tests=[];
const add=(name,fn)=>tests.push({name,fn});
const ok=(v,msg='échec')=>{if(!v)throw new Error(msg)};
add('Banque QCM chargée',()=>ok(Array.isArray(Q)&&Q.length>0));
add('IDs QCM uniques',()=>{const ids=Q.map(q=>q.id);ok(ids.every(Boolean),'ID manquant');ok(new Set(ids).size===ids.length,'doublon détecté')});
add('Structure des QCM valide',()=>{for(const q of Q){ok(Array.isArray(q.choices)&&q.choices.length>=2,`choices ${q.id}`);ok(Array.isArray(q.answers)&&q.answers.length>=1,`answers ${q.id}`);ok(new Set(q.answers).size===q.answers.length,`réponse dupliquée ${q.id}`);ok(q.answers.every(a=>Number.isInteger(a)&&a>=0&&a<q.choices.length),`index réponse ${q.id}`)}});
add('Fonctions principales présentes',()=>['begin','draw','validateQ','startCustom','startSmart','showProgress','showVocals','showCourses74','showFavorites74','openCourse74'].forEach(n=>ok(typeof window[n]==='function',n)));
add('Composants V7 présents',()=>{ok(document.getElementById('v7Mode'),'mode examen');ok(document.getElementById('v7Smart'),'révision intelligente')});
add('Composants V7.1 présents',()=>{ok(document.getElementById('v71SearchCard'),'recherche historique');ok(document.getElementById('v71ReportBtn'),'signalement')});
add('Composants V7.2 présents',()=>{ok(document.getElementById('v72Difficulty'),'difficulté');ok(document.getElementById('v72Progressive'),'progressif');ok(document.getElementById('v72SuggestBtn'),'proposition');ok(window.IFSI_V72?.version==='7.2','API V7.2')});
add('Composants V7.3.1 Vocaux présents',()=>{ok(document.getElementById('vocals'),'section vocaux');ok(document.getElementById('nv'),'onglet vocaux');ok(document.getElementById('vocalList'),'liste vocaux');ok(document.getElementById('vocalPlayer'),'lecteur vocal');ok(document.getElementById('vocalResume'),'reprise vocal');ok(document.getElementById('vocalStateFilter'),'filtre statut');ok(document.getElementById('vocalPlayerListened'),'bouton écouté');ok(document.getElementById('vocalPlayerFavorite'),'bouton favori');ok(window.IFSI_V73?.version==='7.3.1','API V7.3.1')});
add('Catalogue vocaux chargé',()=>{const v=window.IFSI_V73?.getVocals?.()||[];ok(v.length>=29,`${v.length} vocaux`);ok(new Set(v.map(x=>x.id)).size===v.length,'IDs vocaux dupliqués');ok(new Set(v.map(x=>x.driveId)).size===v.length,'Drive IDs dupliqués');ok(v.every(x=>typeof x.courseId==='string'&&x.courseId),'courseId vocal manquant')});
add('État local des vocaux valide',()=>{const s=window.IFSI_V73?.getState?.();ok(s&&Array.isArray(s.listened),'écoutés');ok(Array.isArray(s.favorites),'favoris');ok(typeof window.IFSI_V73?.toggleListened==='function','toggle listened');ok(typeof window.IFSI_V73?.toggleFavorite==='function','toggle favorite')});
add('Composants V7.4 présents',()=>{ok(document.getElementById('v74Dashboard'),'accueil personnalisé');ok(document.getElementById('v74SearchCard'),'recherche globale V2');ok(document.getElementById('courses74'),'liste cours');ok(document.getElementById('course74'),'page cours');ok(document.getElementById('favorites74'),'favoris unifiés');ok(window.IFSI_V74?.version==='7.4','API V7.4');ok(typeof window.IFSI_V74?.showCourses==='function','showCourses');ok(typeof window.IFSI_V74?.showFavorites==='function','showFavorites')});
add('Parcours cours V7.4 alimenté',()=>{const c=window.IFSI_V74?.courses?.()||[];ok(c.length>=10,`${c.length} cours`);ok(new Set(c).size===c.length,'cours dupliqués')});
add('Recherche V7.4 active',()=>{const old=document.getElementById('v71SearchCard'),neo=document.getElementById('v74SearchCard');ok(old&&neo,'cartes recherche');ok(getComputedStyle(old).display==='none','ancienne recherche visible');ok(document.getElementById('v74Search'),'champ V7.4')});
add('Registre V7.4.1 chargé',()=>{ok(window.IFSI_V741?.version==='7.4.1','API V7.4.1');const r=window.IFSI_V741?.getRegistry?.();ok(r&&Array.isArray(r.courses)&&r.courses.length>=16,'registre cours');ok(new Set(r.courses.map(c=>c.id)).size===r.courses.length,'courseId dupliqués')});
add('Rattachements V7.4.1 valides',()=>{const a=window.IFSI_V741?.audit?.();ok(a,'audit absent');ok(a.errors===0,`${a.errors} erreurs de rattachement`);ok(a.questions.unmatched.length===0,'QCM sans courseId');ok(a.vocals.unmatched.length===0,'vocaux sans courseId')});
add('courseId injectés dans les QCM',()=>{ok(Q.every(q=>typeof q.courseId==='string'&&q.courseId),'courseId QCM manquant')});
add('Nouveautés unifiées V7.4.2',()=>{ok(window.IFSI_V742?.version==='7.4.2','API V7.4.2');ok(document.querySelectorAll('#v742Changelog').length===1,'bloc nouveautés unifié absent ou dupliqué');['v72Changelog','v73News','v74News'].forEach(id=>ok(!document.getElementById(id),`ancien bloc encore visible: ${id}`))});
add('Difficultés valides',()=>{const allowed=new Set(['easy','medium','hard']);Q.forEach(q=>ok(allowed.has(window.IFSI_V72.difficulty(q)),`difficulté ${q.id}`))});
add('Schémas respiratoires conservés',()=>['resp_003','resp_013','resp_015'].forEach(id=>ok(Q.some(q=>q.id===id),id)));
add('Valeurs des matières stables',()=>{const s=document.getElementById('course');ok(s&&s.options.length>0);[...s.options].forEach(o=>ok(!/\(\d+\)$/.test(o.value),`valeur modifiée ${o.value}`))});
add('Stockage local opérationnel',()=>{const k='ifsiabc_tnr_probe';localStorage.setItem(k,'ok');ok(localStorage.getItem(k)==='ok');localStorage.removeItem(k)});
add('Pas de doublons d’UI critique',()=>['v72Difficulty','v72Progressive','v72SuggestBtn','v72Online','vocals','nv','vocalPlayer','vocalResume','vocalStateFilter','v74Dashboard','v74SearchCard','courses74','course74','favorites74','v742Changelog'].forEach(id=>ok(document.querySelectorAll('#'+id).length===1,id)));
function run(){const rows=[];let pass=0;for(const t of tests){try{t.fn();rows.push({name:t.name,ok:true});pass++}catch(e){rows.push({name:t.name,ok:false,error:e.message})}}render(rows,pass);console.table(rows)}
function render(rows,pass){let box=document.getElementById('tnrV72');if(!box){box=document.createElement('div');box.id='tnrV72';box.style.cssText='position:fixed;z-index:20000;inset:10px 10px auto auto;width:min(94vw,520px);max-height:88vh;overflow:auto;background:#fff;color:#242332;border:2px solid #6941c6;border-radius:18px;padding:14px;box-shadow:0 18px 70px #0006;font-family:system-ui';document.body.appendChild(box)}const fail=rows.length-pass;box.innerHTML=`<div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><b>🧪 TNR V7.4.2</b><button id="tnrClose" style="border:0;background:#eee8fb;border-radius:999px;width:32px;height:32px">×</button></div><div style="font-size:26px;font-weight:900;color:${fail?'#b42318':'#187a3c'};margin:8px 0">${pass}/${rows.length} OK</div>${rows.map(r=>`<div style="padding:7px 0;border-top:1px solid #eee">${r.ok?'✅':'❌'} <b>${r.name}</b>${r.error?`<div style="font-size:12px;color:#b42318">${r.error}</div>`:''}</div>`).join('')}`;document.getElementById('tnrClose').onclick=()=>box.remove()}
let tries=0;const timer=setInterval(()=>{tries++;const vocals=window.IFSI_V73?.getVocals?.()||[],courses=window.IFSI_V74?.courses?.()||[],reg=window.IFSI_V741?.getRegistry?.();if(Array.isArray(Q)&&Q.length&&window.IFSI_V72&&document.getElementById('v72Difficulty')&&window.IFSI_V73&&vocals.length&&window.IFSI_V74&&courses.length&&reg?.courses?.length&&window.IFSI_V742){clearInterval(timer);setTimeout(run,350)}else if(tries>280){clearInterval(timer);render([{name:'Initialisation de l’application V7.4.2',ok:false,error:'timeout'}],0)}},125);
})();
