(()=>{
'use strict';
const VERSION='7.2';
const K={difficulty:'ifsiabc_v72_difficulty',timer:'ifsiabc_v72_timer',timerStart:'ifsiabc_v72_timer_start',history:'ifsiabc_v72_history',dark:'ifsiabc_v72_dark',resume:'ifsiabc_resume_v1',favs:'ifsiabc_favorites_v1'};
let examAnswers={},sessionStartedAt=0,lastHistoryKey='';
const $72=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const readJSON=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const writeJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const isExam=()=>new URLSearchParams(location.search).get('testschema')!=='1'&&localStorage.getItem('ifsiabc_v7_mode')==='exam';
const favs=()=>new Set(readJSON(K.favs,[]));
const currentQ=()=>{try{return session?.[i]||null}catch{return null}};
function fixKnownContent72(){if(!Array.isArray(Q))return false;const q=Q.find(x=>x?.id==='homeostasie_070');if(!q)return false;q.question='Quels éléments concluent correctement les dernières diapositives ?';q.choices=['Une kaliémie anormale permet à elle seule de connaître sans examen supplémentaire toute la cause.','Tous les mécanismes homéostatiques restent nécessairement aussi efficaces avec l’âge.','Un défaut d’élimination rénale peut contribuer à une hyperkaliémie.','Hypokaliémie et hyperkaliémie peuvent être associées à des troubles cardiaques.','Un déséquilibre homéostatique peut s’accompagner de pathologies.'];q.answers=[2,3,4];q.explanation='Le cours relie les troubles du potassium aux troubles cardiaques et conclut sur les risques des déséquilibres, sans diagnostic automatique. (Support : diapo(s) 90–91.)';return true;}

function addStyles(){if($72('v72css'))return;const s=document.createElement('style');s.id='v72css';s.textContent=`
.v72-tools{display:grid;gap:8px}.v72-row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.v72-toggle{display:flex;align-items:center;justify-content:space-between;gap:10px;border:1px solid #e6e0ef;border-radius:13px;padding:10px 12px;background:#fff}.v72-toggle input{width:20px;height:20px}.v72-diff{font-size:11px;font-weight:900;border-radius:999px;padding:5px 8px;display:inline-block}.v72-easy{background:#eaf8ef;color:#187a3c}.v72-mid{background:#fff4d8;color:#8a6500}.v72-hard{background:#fff0ef;color:#b42318}.v72-personal{background:#eee8fb;color:#6941c6}.v72-exam-nav{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.v72-exam-nav .btn{flex:1;min-width:130px}.v72-timer{font-size:12px;font-weight:900;background:#eef9ff;color:#245675;border-radius:999px;padding:6px 9px}.v72-history{display:grid;gap:8px;margin-top:10px}.v72-history-item{border:1px solid #e6e0ef;border-radius:14px;padding:11px;background:#fff}.v72-history-item .score{font-size:20px;font-weight:900;color:#6941c6}.v72-changelog details{margin-top:7px}.v72-online{margin-left:auto;font-size:11px;font-weight:900;border-radius:999px;padding:5px 8px;background:#eaf8ef;color:#187a3c}.v72-online.off{background:#fff0ef;color:#b42318}.v72-feedback{border:1px solid #cfc2ee;background:#faf8ff}.v72-feedback .btn{width:100%}.v72-modal{position:fixed;inset:0;z-index:10100;background:#12101ce8;display:flex;align-items:center;justify-content:center;padding:16px}.v72-modal.hidden{display:none!important}.v72-dialog{width:min(96vw,540px);background:#fff;border-radius:20px;padding:17px;box-shadow:0 20px 70px #0008}.v72-dialog h3{margin:0 0 9px}.v72-dialog select,.v72-dialog textarea{width:100%;border:1px solid #e6e0ef;border-radius:13px;padding:11px;background:#fff;font:inherit}.v72-dialog textarea{min-height:110px;resize:vertical}.v72-dialog .actions{display:flex;gap:8px;justify-content:flex-end;margin-top:12px;flex-wrap:wrap}
body.v72-dark{--bg:#15131c;--card:#211e2a;--ink:#f4f0fb;--muted:#bbb3c8;--line:#3b3548;background:linear-gradient(#1f1a2d,#15131c 260px);color:var(--ink)}body.v72-dark .card,body.v72-dark .stat,body.v72-dark .sheet,body.v72-dark .choice,body.v72-dark select,body.v72-dark input[type=text],body.v72-dark .v71-result,body.v72-dark .v72-toggle,body.v72-dark .v72-history-item,body.v72-dark .v72-dialog{background:#211e2a;color:#f4f0fb;border-color:#3b3548}body.v72-dark nav{background:#211e2af2;border-color:#3b3548}body.v72-dark .small,body.v72-dark .muted{color:#bbb3c8}body.v72-dark .explain,body.v72-dark .v7-expl{background:#2b2638}body.v72-dark .v7-mode{background:#2b2638;border-color:#3b3548}body.v72-dark .v7-mode button.on{background:#3a3150;color:#d8cbff}body.v72-dark .v71-result .sub{color:#bbb3c8}
@media(max-width:520px){.v72-exam-nav .btn{min-width:105px;font-size:12px}.v72-online{font-size:10px}}
`;document.head.appendChild(s)}

function pedagogicDifficulty(q){
  if(['easy','medium','hard'].includes(q?.difficulty))return q.difficulty;
  const t=((q?.question||'')+' '+(q?.theme||'')+' '+(q?.course||'')).toLowerCase();let score=0;
  if((q?.answers||[]).length>=3)score+=2;else if((q?.answers||[]).length===2)score+=1;
  if(/sch[ée]ma|figure|caryotype|pcr|physiopath|m[ée]canisme|r[ée]gulation|association|associer|interpr|cascade|cons[ée]quence|diagnostic|g[ée]n[ée]tiq|gaz du sang|hom[ée]ostasie/.test(t))score+=2;
  if(/sauf|fausse|fausses|incorrect|ne .* pas|exception/.test(t))score+=1;
  if((q?.choices||[]).some(c=>String(c).length>95))score+=1;
  if(/d[ée]finition|correspond|d[ée]signe|quel est|quelle est/.test(t))score-=1;
  return score>=4?'hard':score>=2?'medium':'easy';
}
function diffLabel(d){return d==='easy'?'🟢 Facile':d==='medium'?'🟠 Intermédiaire':'🔴 Difficile'}
function personalStatus(q){const x=st(),s=x.v7QuestionStats?.[q.id];if(!s||s.answered<2)return null;const r=s.correct/s.answered;if(r<.5)return '⚠️ Difficile pour moi';if(s.answered>=3&&r>=.8)return '✅ Maîtrisée';return '🧠 En cours';}
function filterDifficulty(a){const d=$72('v72Difficulty')?.value||'all';return d==='all'?a:a.filter(q=>pedagogicDifficulty(q)===d)}

function injectControls(){
  const stack=document.querySelector('#home .card.stack');if(stack&&!$72('v72Difficulty')){
    const theme=$72('theme');const sel=document.createElement('select');sel.id='v72Difficulty';sel.innerHTML='<option value="all">Toutes les difficultés</option><option value="easy">🟢 Facile</option><option value="medium">🟠 Intermédiaire</option><option value="hard">🔴 Difficile</option>';if(theme)theme.insertAdjacentElement('afterend',sel);else stack.appendChild(sel);
    const smart=$72('v7Smart');const progressive=document.createElement('button');progressive.id='v72Progressive';progressive.className='btn secondary full';progressive.textContent='📈 Révision progressive';progressive.onclick=startProgressive;if(smart)smart.insertAdjacentElement('afterend',progressive);else stack.appendChild(progressive);
    const timer=document.createElement('label');timer.className='v72-toggle';timer.innerHTML='<span><b>⏱️ Chronomètre</b><div class="small">Afficher le temps de la série et l’enregistrer dans l’historique.</div></span><input id="v72TimerToggle" type="checkbox">';stack.appendChild(timer);$72('v72TimerToggle').checked=localStorage.getItem(K.timer)==='1';$72('v72TimerToggle').onchange=e=>{localStorage.setItem(K.timer,e.target.checked?'1':'0');updateTimerUI()};
    const dark=document.createElement('label');dark.className='v72-toggle';dark.innerHTML='<span><b>🌙 Mode sombre</b><div class="small">Le choix reste enregistré sur cet appareil.</div></span><input id="v72DarkToggle" type="checkbox">';stack.appendChild(dark);$72('v72DarkToggle').checked=localStorage.getItem(K.dark)==='1';$72('v72DarkToggle').onchange=e=>{localStorage.setItem(K.dark,e.target.checked?'1':'0');applyDark()};
  }
  const head=document.querySelector('.head');if(head&&!$72('v72Online')){const b=document.createElement('span');b.id='v72Online';b.className='v72-online';head.appendChild(b);updateOnline()}
  const quizTop=document.querySelector('#quiz .card > .row');if(quizTop&&!$72('v72TimerBadge')){const t=document.createElement('span');t.id='v72TimerBadge';t.className='v72-timer hidden';quizTop.appendChild(t)}
  injectFeedback();injectChangelog();injectHistory();
}
function applyDark(){document.body.classList.toggle('v72-dark',localStorage.getItem(K.dark)==='1')}
function updateOnline(){const b=$72('v72Online');if(!b)return;b.textContent=navigator.onLine?'● En ligne':'● Hors ligne';b.classList.toggle('off',!navigator.onLine)}

function startProgressive(){
  if(!Array.isArray(Q)||!Q.length)return alert('Les questions ne sont pas encore chargées.');let pool=Q;
  const c=$72('course')?.value;if(c)pool=pool.filter(q=>(q.course||q.theme)===c);
  const groups={easy:shuffle(pool.filter(q=>pedagogicDifficulty(q)==='easy')),medium:shuffle(pool.filter(q=>pedagogicDifficulty(q)==='medium')),hard:shuffle(pool.filter(q=>pedagogicDifficulty(q)==='hard'))};
  const count=Math.min(n===999?pool.length:n,pool.length),out=[];const order=['easy','medium','hard'];let idx=0;while(out.length<count&&order.some(k=>groups[k].length)){const k=order[idx%3];if(groups[k].length)out.push(groups[k].shift());idx++}if(!out.length)return alert('Aucune question disponible.');begin(out)
}
window.startProgressive=startProgressive;

function smartPick(pool,count){const x=st(),fs=favs(),errors=new Set(x.errors||[]),qs=x.v7QuestionStats||{},items=pool.map(q=>{let w=1;if(errors.has(q.id))w+=7;if(fs.has(q.id))w+=3;const s=qs[q.id];if(!s)w+=2;else w+=(1-(s.correct/Math.max(1,s.answered)))*4;if(personalStatus(q)==='⚠️ Difficile pour moi')w+=3;return{q,w}}),out=[];while(items.length&&out.length<count){let total=items.reduce((a,b)=>a+b.w,0),r=Math.random()*total,p=0;for(;p<items.length;p++){r-=items[p].w;if(r<=0)break}out.push(items.splice(Math.min(p,items.length-1),1)[0].q)}return out}
function startSmartV72(){let pool=Array.isArray(Q)?Q:[];const c=$72('course')?.value;if(c)pool=pool.filter(q=>(q.course||q.theme)===c);pool=filterDifficulty(pool);const count=Math.min(n===999?50:n,pool.length);const a=smartPick(pool,count);if(!a.length)return alert('Aucune question disponible avec ces filtres.');begin(a)}

function saveCurrentExam(allowEmpty=true){const q=currentQ();if(!q)return false;const sel=[...document.querySelectorAll('#choices input:checked')].map(x=>+x.value);if(!allowEmpty&&!sel.length)return false;examAnswers[q.id]=sel;saveExamResume();return true}
function saveExamResume(){if(!isExam()||!session?.length)return;localStorage.setItem(K.resume,JSON.stringify({ids:session.map(q=>q.id),index:i,results:[],savedAt:Date.now(),mode:'exam',examAnswers,examStartedAt:sessionStartedAt||Date.now()}))}
function examGo(delta){if(!isExam())return;saveCurrentExam(true);const ni=Math.max(0,Math.min(session.length-1,i+delta));if(ni===i)return;i=ni;done=false;draw();saveExamResume()}
function recordExamResult(q,ok){const x=st();x.errors=Array.isArray(x.errors)?x.errors:[];x.reviewStreaks=x.reviewStreaks||{};x.themes=x.themes||{};x.v7QuestionStats=x.v7QuestionStats||{};const was=x.errors.includes(q.id)||Object.prototype.hasOwnProperty.call(x.reviewStreaks,q.id);x.answered=(x.answered||0)+1;if(ok)x.correct=(x.correct||0)+1;if(ok&&was){const streak=(x.reviewStreaks[q.id]||0)+1;if(streak>=2){x.errors=x.errors.filter(v=>v!==q.id);delete x.reviewStreaks[q.id]}else{x.reviewStreaks[q.id]=streak;if(!x.errors.includes(q.id))x.errors.push(q.id)}}else if(!ok){if(!x.errors.includes(q.id))x.errors.push(q.id);x.reviewStreaks[q.id]=0}const k=(q.course||'')+' — '+q.theme;x.themes[k]??={answered:0,correct:0};x.themes[k].answered++;if(ok)x.themes[k].correct++;const s=x.v7QuestionStats[q.id]||{answered:0,correct:0};s.answered++;if(ok)s.correct++;s.last=Date.now();x.v7QuestionStats[q.id]=s;save(x)}
function letters(a){return (a||[]).map(j=>'ABCDE'[j]).join(', ')||'Aucune'}
function finishExamV72(){saveCurrentExam(true);const unanswered=session.filter(q=>!(q.id in examAnswers)||!examAnswers[q.id].length).length;if(unanswered&&!confirm(`${unanswered} question${unanswered>1?'s':''} sans réponse. Terminer quand même ?`))return;const oks=session.map(q=>same(examAnswers[q.id]||[],q.answers));oks.forEach((ok,j)=>recordExamResult(session[j],ok));res=oks;localStorage.removeItem(K.resume);const c=oks.filter(Boolean).length;show('result');$72('score').textContent=Math.round(c/session.length*100)+'%';$72('detail').textContent=c+' / '+session.length+' bonnes réponses';renderExamReviewV72();try{fill()}catch{}stopTimer(false)}
function renderExamReviewV72(){const box=$72('v7ExamReview');if(!box)return;box.classList.remove('hidden');box.innerHTML='<h3 style="margin:12px 0 6px">Corrigé détaillé</h3><div class="small">Correction affichée uniquement après la fin de l’examen.</div>'+session.map((q,j)=>{const u=examAnswers[q.id]||[],ok=same(u,q.answers);return `<details><summary class="${ok?'ok':'bad'}">${ok?'✅':'❌'} Q${q.number||j+1} — ${esc(q.course||q.theme||'')}</summary><div class="v7-answer"><b>Ta réponse :</b> ${esc(letters(u))}<br><b>Bonne réponse :</b> ${esc(letters(q.answers))}</div><div class="v7-expl">${esc(q.explanation||'')}</div></details>`}).join('')}
function setupExamNav(){let box=$72('v72ExamNav');if(!box){box=document.createElement('div');box.id='v72ExamNav';box.className='v72-exam-nav';box.innerHTML='<button id="v72Prev" class="btn outline" type="button">← Précédente</button><button id="v72Forward" class="btn primary" type="button">Suivante →</button>';$72('choices')?.insertAdjacentElement('afterend',box);$72('v72Prev').onclick=()=>examGo(-1);$72('v72Forward').onclick=()=>examGo(1)}box.classList.toggle('hidden',!isExam());if(isExam()){$72('v72Prev').disabled=i===0;$72('v72Forward').classList.toggle('hidden',i>=session.length-1);const valid=$72('valid');if(valid){valid.textContent='Terminer l’examen';valid.classList.toggle('hidden',i<session.length-1)}$72('next')?.classList.add('hidden')}}

function startTimer(){sessionStartedAt=Date.now();localStorage.setItem(K.timerStart,String(sessionStartedAt));updateTimerUI()}
function stopTimer(clear=true){updateTimerUI();if(clear)localStorage.removeItem(K.timerStart)}
function timerStart(){return Number(localStorage.getItem(K.timerStart)||sessionStartedAt||0)}
function fmtTime(ms){const s=Math.max(0,Math.floor(ms/1000)),m=Math.floor(s/60),r=s%60;return `${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`}
function updateTimerUI(){const b=$72('v72TimerBadge');if(!b)return;const on=localStorage.getItem(K.timer)==='1',start=timerStart();b.classList.toggle('hidden',!on||!start||$72('quiz')?.classList.contains('hidden'));if(on&&start)b.textContent='⏱️ '+fmtTime(Date.now()-start)}
setInterval(updateTimerUI,1000);

function injectHistory(){const p=$72('progress')?.querySelector('.card');if(!p||$72('v72History'))return;const box=document.createElement('div');box.id='v72History';box.innerHTML='<h3 style="margin-top:18px">📈 Historique des sessions</h3><div class="small">20 dernières sessions enregistrées sur cet appareil.</div><div id="v72HistoryList" class="v72-history"></div>';p.appendChild(box);renderHistory()}
function renderHistory(){const box=$72('v72HistoryList');if(!box)return;const h=readJSON(K.history,[]);box.innerHTML=h.length?h.map(x=>`<div class="v72-history-item"><div class="row"><div><b>${esc(x.mode==='exam'?'🎓 Examen':'📘 Entraînement')}</b><div class="small">${esc(x.date)} • ${esc(x.course||'Mix matières')}</div></div><div class="score">${x.score}%</div></div><div class="small">${x.correct}/${x.total} bonnes réponses${x.duration?' • '+esc(x.duration):''}</div></div>`).join(''):'<div class="small">Aucune session terminée pour le moment.</div>'}
function recordHistory(){if(!session?.length||!res?.length)return;const correct=res.filter(Boolean).length,total=session.length,start=timerStart(),key=session.map(q=>q.id).join('|')+'|'+correct+'|'+(start||'');if(key===lastHistoryKey)return;lastHistoryKey=key;const courses=[...new Set(session.map(q=>q.course||q.theme).filter(Boolean))];const h=readJSON(K.history,[]);h.unshift({ts:Date.now(),date:new Date().toLocaleString('fr-FR'),mode:isExam()?'exam':'train',course:courses.length===1?courses[0]:'Mix matières',correct,total,score:Math.round(correct/total*100),duration:start?fmtTime(Date.now()-start):''});writeJSON(K.history,h.slice(0,20));renderHistory();localStorage.removeItem(K.timerStart)}

function injectFeedback(){const home=$72('home');if(!home||$72('v72SuggestBtn'))return;const appTitle=[...home.querySelectorAll('.section')].find(x=>x.textContent.trim()==='Application');const card=document.createElement('div');card.className='card v72-feedback';card.innerHTML='<b>💡 Une idée pour améliorer l’appli ?</b><div class="small" style="margin:5px 0 10px">Propose une évolution. Le message sera préparé pour le groupe « Problème technique ».</div><button id="v72SuggestBtn" class="btn secondary">💡 Proposer une amélioration</button>';if(appTitle)appTitle.insertAdjacentElement('afterend',card);else home.appendChild(card);$72('v72SuggestBtn').onclick=openSuggestion;ensureSuggestionModal();patchIncident()}
function ensureSuggestionModal(){if($72('v72SuggestModal'))return;const m=document.createElement('div');m.id='v72SuggestModal';m.className='v72-modal hidden';m.innerHTML='<div class="v72-dialog"><h3>💡 Proposer une amélioration</h3><select id="v72SuggestType"><option>QCM / contenu</option><option>Ergonomie / navigation</option><option>Progression / statistiques</option><option>Fiches / infographies</option><option>Nouvelle fonctionnalité</option><option>Autre</option></select><textarea id="v72SuggestText" placeholder="Décris ton idée…"></textarea><div class="small" style="margin-top:8px">Aucune donnée n’est envoyée automatiquement. Après « Partager », choisis WhatsApp puis le groupe « Problème technique ».</div><div class="actions"><button id="v72SuggestCancel" class="btn outline">Annuler</button><button id="v72SuggestShare" class="btn primary">Partager vers Problème technique</button></div></div>';document.body.appendChild(m);m.onclick=e=>{if(e.target===m)m.classList.add('hidden')};$72('v72SuggestCancel').onclick=()=>m.classList.add('hidden');$72('v72SuggestShare').onclick=shareSuggestion}
function openSuggestion(){$72('v72SuggestText').value='';$72('v72SuggestModal').classList.remove('hidden')}
async function shareText(title,text,modal){try{if(navigator.share){await navigator.share({title,text});modal?.classList.add('hidden');return}await navigator.clipboard.writeText(text);alert('Message copié. Colle-le dans le groupe « Problème technique ».');modal?.classList.add('hidden')}catch(e){if(e?.name==='AbortError')return;try{await navigator.clipboard.writeText(text);alert('Message copié dans le presse-papiers.')}catch{prompt('Copie ce message :',text)}}}
function shareSuggestion(){const type=$72('v72SuggestType').value,idea=$72('v72SuggestText').value.trim();if(!idea)return alert('Décris ton idée avant de la partager.');const text=`💡 PROPOSITION – IFSI ABC\nVersion : V${window.IFSI_APP_VERSION||VERSION}\nDate : ${new Date().toLocaleString('fr-FR')}\nCatégorie : ${type}\nProposition : ${idea}\n\n➡️ À poster dans le groupe « Problème technique ».\nAppli : ${location.origin+location.pathname}`;shareText(`Proposition IFSI ABC V${VERSION}`,text,$72('v72SuggestModal'))}
function patchIncident(){const m=$72('v71ReportModal'),b=$72('v71ReportShare');if(!m||!b)return false;const note=[...m.querySelectorAll('.small')].find(x=>x.textContent.includes('Aucune donnée'));if(note)note.innerHTML='Aucune donnée n’est envoyée automatiquement.<br><b>Après « Partager », choisis WhatsApp puis le groupe « Problème technique ».</b>';b.textContent='Partager vers Problème technique';b.onclick=()=>{const q=currentQ();if(!q)return;const type=$72('v71ReportType')?.value||'Autre',detail=$72('v71ReportNote')?.value.trim()||'';const text=`🚩 INCIDENT – IFSI ABC\nVersion : V${VERSION}\nDate : ${new Date().toLocaleString('fr-FR')}\nCours : ${q.course||q.theme||''}\nQuestion : ${q.number?'Q'+q.number:'—'}\nID : ${q.id}\nNiveau estimé : ${diffLabel(pedagogicDifficulty(q))}\nType : ${type}\nÉnoncé : ${q.question}${detail?'\nDétail : '+detail:''}\n\n➡️ À poster dans le groupe « Problème technique ».\nAppli : ${location.origin+location.pathname}`;shareText(`Incident IFSI ABC V${window.IFSI_APP_VERSION||VERSION}`,text,m)};return true}

function injectChangelog(){const home=$72('home');if(!home||$72('v72Changelog'))return;const card=document.createElement('div');card.id='v72Changelog';card.className='card v72-changelog';card.innerHTML='<b>🆕 Nouveautés V7.2</b><details><summary class="small" style="cursor:pointer;margin-top:6px">Voir les changements</summary><div class="small" style="margin-top:8px;line-height:1.55">• Navigation Précédente/Suivante en examen<br>• Chronomètre facultatif et historique des sessions<br>• Difficulté pédagogique estimée + difficulté personnelle<br>• Filtres de difficulté et révision progressive<br>• Proposition d’amélioration et signalement standardisé<br>• Mode sombre et indicateur hors ligne<br>• TNR intégrés pour contrôler les régressions</div></details>';const app=[...home.querySelectorAll('.section')].find(x=>x.textContent.trim()==='Application');if(app)app.insertAdjacentElement('beforebegin',card);else home.appendChild(card)}

const originalStartCustom=window.startCustom;
window.startCustom=function(){let a=Q.filter(q=>(q.course||q.theme)===$72('course').value);if($72('theme').value!=='Tous les sous-thèmes')a=a.filter(q=>q.theme===$72('theme').value);a=filterDifficulty(a);if(!a.length)return alert('Aucune question disponible avec ces filtres.');begin(shuffle(a).slice(0,Math.min(n,a.length)))};
window.startSmart=startSmartV72;

const prevBegin=begin;
begin=function(a){examAnswers={};sessionStartedAt=Date.now();localStorage.setItem(K.timerStart,String(sessionStartedAt));prevBegin(a);if(isExam())saveExamResume();updateTimerUI()};
const prevDraw=draw;
draw=function(){prevDraw();const q=currentQ();if(q){$72('v72QuestionMeta')?.remove();const d=pedagogicDifficulty(q),p=personalStatus(q),x=document.createElement('div');x.id='v72QuestionMeta';x.className='v72-row';x.style.marginTop='8px';x.innerHTML=`<span class="v72-diff ${d==='easy'?'v72-easy':d==='medium'?'v72-mid':'v72-hard'}">${diffLabel(d)}</span>${p?`<span class="v72-diff v72-personal">${esc(p)}</span>`:''}`;$72('expected')?.insertAdjacentElement('afterend',x)}setupExamNav();if(isExam()){const sel=examAnswers[q?.id]||[];document.querySelectorAll('#choices input').forEach(inp=>inp.checked=sel.includes(+inp.value))}updateTimerUI()};
const prevValidate=validateQ;
validateQ=function(){if(!isExam())return prevValidate();if(i<session.length-1){saveCurrentExam(true);return examGo(1)}finishExamV72()};
const prevResume=window.resumeSession;
window.resumeSession=function(){const r=readJSON(K.resume,null);const exam=r?.mode==='exam';const out=typeof prevResume==='function'?prevResume():undefined;if(exam){examAnswers=r.examAnswers||{};sessionStartedAt=r.examStartedAt||Date.now();localStorage.setItem(K.timerStart,String(sessionStartedAt));setTimeout(()=>{draw();saveExamResume()},0)}return out};

function observeResults(){const r=$72('result');if(!r||r.dataset.v72obs)return;r.dataset.v72obs='1';new MutationObserver(()=>{if(!r.classList.contains('hidden'))setTimeout(recordHistory,30)}).observe(r,{attributes:true,attributeFilter:['class']})}
function setVersion(){const u=$72('update');if(u&&Array.isArray(Q)&&Q.length)u.textContent='Application prête • V7.2 locale : examen navigable, difficultés, historique, feedback et TNR.';const b=u?.parentElement?.querySelector('b');if(b)b.textContent='V7.2 local'}
function ready(){addStyles();applyDark();injectControls();observeResults();patchIncident();fixKnownContent72();setVersion();return Array.isArray(Q)&&Q.length>0}
window.IFSI_V72={version:VERSION,difficulty:pedagogicDifficulty,personalStatus,recordHistory,runProgressive:startProgressive};
addStyles();applyDark();injectControls();observeResults();let tries=0;const t=setInterval(()=>{tries++;if(ready()||tries>120)clearInterval(t)},125);window.addEventListener('online',updateOnline);window.addEventListener('offline',updateOnline);window.addEventListener('storage',()=>{applyDark();renderHistory();updateTimerUI()});
})();