import fs from 'node:fs';
import zlib from 'node:zlib';

const read=p=>fs.readFileSync(p,'utf8');
const json=p=>JSON.parse(read(p));
const assert=(v,msg)=>{if(!v)throw new Error(msg)};
const schemaRegex=/\b(sch[ée]ma|schema|figure|illustration|diagramme|image\s+ci|ci-dessous|boucle\s+anonyme)\b/i;
const keepQuestion=q=>{const t=q?.question||'';if(schemaRegex.test(t))return false;if(/\brep[eè]re\b/i.test(t)&&/(association|associer|structure|lettre)/i.test(t))return false;return true};
function gzipBody(raw){let p=10,flags=raw[3]||0;if(flags&4){const n=raw[p]|(raw[p+1]<<8);p+=2+n}if(flags&8)while(p<raw.length&&raw[p++]);if(flags&16)while(p<raw.length&&raw[p++]);if(flags&2)p+=2;return raw.subarray(p,-8)}
function parsePackText(txt){try{return JSON.parse(txt)}catch(first){const body=txt.trim().replace(/^\s*\[/,'').replace(/\]\s*$/,'');const parts=body.split(/}\s*,\s*\{"id":/);const recovered=[];for(let i=0;i<parts.length;i++){let s=(i?'{"id":':'')+parts[i];if(!s.trim().endsWith('}'))s+='}';try{const q=JSON.parse(s);if(q&&q.id)recovered.push(q)}catch{}}if(recovered.length)return recovered;throw first}}
function decodePackFile(p){const source=read(p).trim();if(source.startsWith('[')||source.startsWith('{'))return parsePackText(source);const raw=Buffer.from(source,'base64');let txt;if(raw.length>2&&raw[0]===0x1f&&raw[1]===0x8b){try{txt=zlib.gunzipSync(raw).toString('utf8')}catch{txt=zlib.inflateRawSync(gzipBody(raw)).toString('utf8')}}else txt=raw.toString('utf8');return parsePackText(txt)}

let base=[];
for(let i=1;i<=5;i++)base.push(...json(`questions-${i}.json`));
let extras=[],skipped=[];
for(const i of [1,2,3,4,5,6,7,...Array.from({length:30},(_,j)=>j+9)]){const p=`qextra-${String(i).padStart(2,'0')}.txt`;if(!fs.existsSync(p))continue;try{const parsed=decodePackFile(p);extras.push(...(Array.isArray(parsed)?parsed:(parsed.questions||[])))}catch(e){skipped.push(`${p}: ${e.message}`)}}
const v820RawPacks=[];for(let i=12;i<=38;i++){const p=`qextra-${String(i).padStart(2,'0')}.txt`;assert(fs.existsSync(p),`Pack V8.20 absent: ${p}`);const a=decodePackFile(p);assert(Array.isArray(a)&&a.length>0,`Pack V8.20 vide: ${p}`);v820RawPacks.push(...a)}
assert(v820RawPacks.length>=1000,`Banque V8.20 trop petite: ${v820RawPacks.length}`);
for(const q of v820RawPacks){assert(q.courseId,`courseId V8.20 absent: ${q.id}`);assert(Array.isArray(q.choices)&&q.choices.length>=4,`Choix V8.20 invalides: ${q.id}`);assert(!q.choices.some(x=>/CORRIG[ÉE]|GRILLE (?:SYNTH[ÉE]TIQUE|DES R[ÉE]PONSES)|IFSI Antoine Béclère[\s\S]*Page\s+\d+/i.test(x)),`Fragment PDF parasite dans ${q.id}`)}
base=base.filter(keepQuestion);extras=extras.filter(keepQuestion);
const seen=new Set(base.map(q=>q.id));const runtime=[...base];
for(const q of extras)if(!seen.has(q.id)){runtime.push(q);seen.add(q.id)}
const schemaIds=['resp_003','resp_013','resp_015'];
const schemaSource=read('schema-v10.js');
const officialRespAssets=['resp-official-overview-learn.jpg','resp-official-overview-test.jpg','resp-official-bronchial-learn.jpg','resp-official-bronchial-test.jpg','resp-official-epithelium-test.jpg'];
for(const p of officialRespAssets)assert(fs.existsSync(p),`Visuel respiratoire officiel absent: ${p}`);

for(const id of schemaIds){assert(schemaSource.includes(id),`Schéma ${id} absent`);assert(!seen.has(id),`Doublon schéma ${id}`)}
assert(runtime.length+schemaIds.length>=1400,`Banque trop petite: ${runtime.length+schemaIds.length}${skipped.length?' • packs ignorés '+skipped.join(' | '):''}`);
assert(new Set(runtime.map(q=>q.id)).size===runtime.length,'IDs QCM dupliqués');
for(const q of runtime){assert(typeof q.id==='string'&&q.id,'Question sans ID');assert(typeof q.question==='string'&&q.question.trim(),'Énoncé absent');assert(Array.isArray(q.choices)&&q.choices.length>=2,`Choix invalides ${q.id}`);assert(Array.isArray(q.answers)&&q.answers.length>=1,`Réponse absente ${q.id}`);assert(q.answers.every(a=>Number.isInteger(a)&&a>=0&&a<q.choices.length),`Réponse invalide ${q.id}`)}
const calcQuestions=runtime.filter(q=>q.courseId==='calculs_doses_mathematiques'||/calculs? de doses|math[eé]matiques/i.test(q.course||''));
assert(calcQuestions.length>=220,`Banque calculs insuffisante: ${calcQuestions.length}${skipped.length?' • packs ignorés '+skipped.join(' | '):''}`);

const respiratory=new Map(runtime.filter(q=>q.course==='Système respiratoire').map(q=>[q.id,q]));
assert(respiratory.size===47,`Questions respiratoires textuelles inattendues: ${respiratory.size}`);
assert(JSON.stringify(respiratory.get('resp_049')?.answers)==='[0,3]','Réponses resp_049 non synchronisées');
assert(JSON.stringify(respiratory.get('resp_050')?.answers)==='[0,1,3]','Réponses resp_050 non synchronisées');
assert(new Set([...respiratory.values()].map(q=>q.theme)).size>=5,'Thématiques respiratoires insuffisantes');
const nervous=new Map(runtime.filter(q=>q.courseId==='systeme_nerveux').map(q=>[q.id,q]));
assert(nervous.size===49,`Questions système nerveux inattendues: ${nervous.size}`);
assert(JSON.stringify(nervous.get('nervous_001')?.answers)==='[1,2,3]','Réponses nervous_001 non synchronisées');
assert(JSON.stringify(nervous.get('nervous_049')?.answers)==='[0,1,2,3]','Réponses nervous_049 non synchronisées');
assert(!/sch[ée]ma/i.test(nervous.get('nervous_010')?.question||''),'nervous_010 doit être autonome sans schéma externe');
assert(!/sch[ée]ma/i.test(nervous.get('nervous_031')?.question||''),'nervous_031 doit être autonome sans schéma externe');

const registry=json('course-registry-v741.json');
assert(registry.version==='8.27','Registre version incorrecte');
assert(Array.isArray(registry.courses)&&registry.courses.length>=35,'Registre trop petit');
const courseIds=new Set(registry.courses.map(c=>c.id));
assert(courseIds.size===registry.courses.length,'courseId dupliqués');
assert(courseIds.has('calculs_doses_mathematiques'),'CourseId calculs absent');assert(courseIds.has('ist_hors_vih'),'CourseId IST hors VIH absent');assert(runtime.filter(q=>q.courseId==='ist_hors_vih').length===56,'Banque IST hors VIH inattendue');assert(courseIds.has('systeme_digestif'),'CourseId digestif absent');assert(courseIds.has('douleur'),'CourseId douleur absent');assert(courseIds.has('epistemologie_savoirs'),'CourseId épistémologie absent');
const infographics=json('infographics.json');
const nervousInfos=infographics.filter(x=>x.courseId==='systeme_nerveux');
assert(nervousInfos.length===4,`Infographies système nerveux inattendues: ${nervousInfos.length}`);
for(const title of ['Organisation générale du système nerveux','Système nerveux central','Système nerveux périphérique','Fonctions neurologiques'])assert(nervousInfos.some(x=>x.displayTitle===title),`Infographie système nerveux absente: ${title}`);
const v820MinCounts={epistemologie_savoirs:110,histoire_profession_infirmiere:45,ethique_infirmiere:45,prevention_ias_asepsie:120,infections_cutanees:45,infections_neuro_meningees:30,appareil_locomoteur:45,traumatologie:80,arthrose:35,chirurgie_orthopedique:25,rhumatismes_inflammatoires:30,pathologies_microcristallines_osteoporose:40,systeme_digestif:65,grands_brules:30,parametres_vitaux:45,douleur:25,competences_psychosociales:25,systeme_cardiovasculaire:53};
for(const [id,min] of Object.entries(v820MinCounts)){const n=runtime.filter(q=>q.courseId===id).length;assert(n>=min,`V8.20 course QCM insuffisant ${id}: ${n}/${min}`)}
const expectedInfoCounts={cellules_tissus:9,niveaux_organisation:2,prevention_ias_asepsie:8,virus:1,infections_cutanees:3,infections_neuro_meningees:7,infections_urinaires:3,diagnostic_bacteriologie:3};
for(const [id,min] of Object.entries(expectedInfoCounts)){const n=infographics.filter(x=>x.courseId===id).length;assert(n>=min,`Infographies V8.20 insuffisantes ${id}: ${n}/${min}`)}
const vocals=json('vocals.json');
assert(vocals.length>=29,'Catalogue vocaux trop petit');
for(const v of vocals){assert(courseIds.has(v.courseId),`courseId vocal invalide ${v.id}`);assert(v.driveId?.length>10,`Drive ID vocal invalide ${v.id}`)}

const sw=read('sw.js');
for(const marker of ['./app-version-v742.js','./v72-pack.js','./vocals-v73.js','./v74-pack.js','./course-registry-v741.js','./changelog-v742.js','./v75-smart.js','./v76-home.js','./analytics-v77.js','./v79-themes.js','./calculs-parcours-v1.js','./v81-suite.js','./v82-nav-anatomy.js','./v83-anatomy-interactive.js','./v84-respiratory-polish.js','./v85-home-lite.js','./v86-home-clean.js','./v87-settings.js','./v813-home-discovery.js','./v814-respiratory-atlas.js','./v815-urinary-atlas.js','./v816-endocrine-atlas.js','./v817-immune-atlas.js','./v822-nervous-atlas.js','./v823-cardiovascular-atlas.js','./v824-digestive-atlas.js','./v829-locomotor-atlas.js','./assets/locomotor/locomotor-01.webp','./assets/locomotor/locomotor-02.webp','./assets/locomotor/locomotor-03.webp','./assets/locomotor/locomotor-04.webp','./assets/locomotor/locomotor-05.webp','./assets/locomotor/locomotor-06.webp','./assets/locomotor/locomotor-07.webp','./assets/locomotor/locomotor-08.webp','./assets/locomotor/locomotor-09.webp','./assets/locomotor/locomotor-10.webp','./assets/locomotor/locomotor-11.webp','./assets/locomotor/locomotor-12.webp','./assets/locomotor/locomotor-13.webp','./assets/locomotor/locomotor-14.webp','./assets/locomotor/locomotor-15.webp','./assets/locomotor/locomotor-16.webp','./assets/locomotor/locomotor-17.webp','./assets/locomotor/locomotor-18.webp','./assets/locomotor/locomotor-19.webp','./assets/locomotor/locomotor-20.webp','./v826-changelog.js','./v821-resource-audit.js','./v828-revision-clean.js','./v828-changelog.js','./v829-changelog.js','./v830-changelog.js','./v8301-changelog.js','./v8302-changelog.js','./resource-audit-v821.json','./qextra-11.txt','./qextra-12.txt','./qextra-13.txt','./qextra-14.txt','./qextra-15.txt','./qextra-16.txt','./qextra-17.txt','./qextra-18.txt','./qextra-19.txt','./qextra-20.txt','./qextra-21.txt','./qextra-22.txt','./qextra-23.txt','./qextra-24.txt','./qextra-25.txt','./qextra-26.txt','./qextra-27.txt','./qextra-28.txt','./qextra-29.txt','./qextra-30.txt','./qextra-31.txt','./qextra-32.txt','./qextra-33.txt','./qextra-34.txt','./qextra-35.txt','./qextra-36.txt','./qextra-37.txt','./qextra-38.txt','./build-meta.json','./tnr-v72.js'])assert(sw.includes(marker),`Asset absent du SW: ${marker}`);
assert(sw.includes("ifsi-abc-v8-30-2-local-95"),'Cache V8.30.2 local-95 absent');
assert(sw.includes("'deflate-raw'"),'Récupération gzip dégradé absente du SW');
assert(sw.includes('parsePackText'),'Récupération JSON partielle absente du SW');
assert(sw.indexOf('analytics-v77.js')<sw.indexOf('v79-themes.js'),'V7.9 doit être chargée après analytics');
assert(sw.indexOf('v79-themes.js')<sw.indexOf('calculs-parcours-v1.js'),'Calculs doit être chargé après V7.9');
assert(sw.indexOf('calculs-parcours-v1.js')<sw.indexOf('v81-suite.js'),'V8.1 doit être chargée après le parcours calculs');
assert(sw.indexOf('v81-suite.js')<sw.indexOf('v82-nav-anatomy.js'),'V8.2 doit être chargée après V8.1');
assert(sw.indexOf('v82-nav-anatomy.js')<sw.indexOf('v83-anatomy-interactive.js'),'Anatomie interactive doit être chargée après V8.2');
assert(sw.indexOf('v83-anatomy-interactive.js')<sw.indexOf('v84-respiratory-polish.js'),'V8.4 respiratoire doit être chargée après l’anatomie interactive');
assert(sw.indexOf('v84-respiratory-polish.js')<sw.indexOf('v85-home-lite.js'),'V8.5 accueil doit être chargé après V8.4');
assert(sw.indexOf('v85-home-lite.js')<sw.indexOf('v86-home-clean.js'),'V8.6 doit être chargée après V8.5');
assert(sw.indexOf('v86-home-clean.js')<sw.indexOf('v87-settings.js'),'V8.7 doit être chargée après V8.6');
assert(sw.indexOf('v87-settings.js')<sw.indexOf('v813-home-discovery.js'),'Accueil V8.13 doit être chargé après Paramètres');assert(sw.indexOf('v813-home-discovery.js')<sw.indexOf('v814-respiratory-atlas.js'),'Atlas respiratoire V8.14 doit être chargé après l’accueil V8.13');assert(sw.indexOf('v814-respiratory-atlas.js')<sw.indexOf('v815-urinary-atlas.js'),'Atlas urinaire V8.15 doit être chargé après l’atlas respiratoire');assert(sw.indexOf('v815-urinary-atlas.js')<sw.indexOf('v816-endocrine-atlas.js'),'Atlas endocrinien V8.16 doit être chargé après l’atlas urinaire');assert(sw.indexOf('v816-endocrine-atlas.js')<sw.indexOf('v817-immune-atlas.js'),'Atlas immunitaire V8.17 doit être chargé après l’atlas endocrinien');assert(sw.indexOf('v817-immune-atlas.js')<sw.indexOf('v822-nervous-atlas.js'),'Atlas nerveux V8.22 doit être chargé après l’atlas immunitaire');assert(sw.indexOf('v822-nervous-atlas.js')<sw.indexOf('v823-cardiovascular-atlas.js'),'Atlas cardiovasculaire V8.23 doit être chargé après l’atlas nerveux');assert(sw.indexOf('v823-cardiovascular-atlas.js')<sw.indexOf('v824-digestive-atlas.js'),'Atlas digestif V8.24 doit être chargé après l’atlas cardiovasculaire');assert(sw.indexOf('v824-digestive-atlas.js')<sw.indexOf('v829-locomotor-atlas.js'),'Atlas locomoteur V8.29 doit être chargé après l’atlas digestif');assert(sw.indexOf('v829-locomotor-atlas.js')<sw.indexOf('v826-changelog.js'),'Journal V8.26 doit rester chargé après les atlas');assert(sw.indexOf('v826-changelog.js')<sw.indexOf('v821-resource-audit.js'),'Audit ressources doit être chargé après le journal V8.26');assert(sw.indexOf('v821-resource-audit.js')<sw.indexOf('v828-revision-clean.js'),'Correctif Révision V8.28 doit être chargé après l’audit ressources');assert(sw.indexOf('v828-revision-clean.js')<sw.indexOf('v828-changelog.js'),'Changelog V8.28 doit être chargé après le correctif Révision');assert(sw.indexOf('v828-changelog.js')<sw.indexOf('v829-changelog.js'),'Changelog V8.29 doit être chargé après V8.28');assert(sw.indexOf('v829-changelog.js')<sw.indexOf('v830-changelog.js'),'Changelog V8.30 doit être chargé après V8.29');assert(sw.indexOf('v830-changelog.js')<sw.indexOf('v8301-changelog.js'),'Changelog V8.30.1 doit être chargé après V8.30');assert(sw.indexOf('v8301-changelog.js')<sw.indexOf('v8302-changelog.js'),'Changelog V8.30.2 doit être chargé après V8.30.1');assert(sw.indexOf('v8302-changelog.js')<sw.indexOf('tnr-v72.js'),'V8.30.2 doit être chargé avant le TNR navigateur');
const versionModule=read('app-version-v742.js');
for(const marker of ["const VERSION='8.30.2'",'IFSI_APP_VERSION','consultation HD','build-meta.json'])assert(versionModule.includes(marker),`Version V8.30.2 incomplète: ${marker}`);
const changelog=read('changelog-v742.js');
for(const marker of ["const VERSION='8.27'",'v826Change','V8.26 — IST hors VIH et mises à jour fiables','v823Change','V8.23 — Système cardiovasculaire complet','v822Change','V8.22 — Atlas anatomique du système nerveux','v821Change','V8.21 — Audit automatique Drive ↔ Application','v820Change','V8.20 — Synchronisation Drive → application','v8191Change','V8.19.1 — Accueil allégé','v819Change','V8.19 — Nettoyage structurel','v818Change','V8.18 — Système nerveux complété','v817Change','V8.17 — Atlas immunitaire HD 8 planches','v816Change','V8.16 — Atlas endocrinien HD 8 planches','v8151Change','V8.15.1 — Correctif atlas urinaire','v815Change','V8.15 — Atlas urinaire 8 planches','v8141Change','V8.14.1 — Correctif atlas respiratoire','v814Change','V8.14 — Atlas respiratoire 8 planches','v813Change','V8.13 — Accueil : recherche cours & nouveautés','v812Change','V8.12 — Planches anatomiques multi-systèmes','v8114Change','V8.11.4 — Module respiratoire HD complet','v8113Change','V8.11.3 — Planche HD Voies respiratoires','v8112Change','V8.11.2 — Zoom plein écran des planches','v8111Change','V8.11.1 — Test réel de la planche Voies respiratoires','v811Change','V8.11 — Planches respiratoires premium','v810Change','V8.10 — Cours par domaine & Anatomie simplifiée','v891Change','V8.9.1 — Mathématiques dans le domaine E','v89Change','V8.9 — Mes cours rangés par UE','v884Change','V8.8.4 — Hotfix gel immédiat','v883Change','V8.8.3 — Correctif performance mobile','v882Change','V8.8.2 — Hotfix anti-gel mobile','v881Change','V8.8.1 — Stabilité mobile','v88Change','V8.8 — Audit et rangement des ressources','v87Change','V8.7 — Onglet Paramètres','v86Change','V8.6 — Accueil minimal','v85Change','V8.5 — Accueil allégé','v84Change','V8.4 — Système respiratoire enrichi','v83Change','v82Change','v81Change','v80Change','v79Change','IFSI_CHANGELOG'])assert(changelog.includes(marker),`Changelog historique incomplet: ${marker}`);
const v826Changelog=read('v826-changelog.js');for(const marker of ['v826Change','V8.26 — IST hors VIH et mises à jour fiables',"badge.textContent='V8.26'"])assert(v826Changelog.includes(marker),`Changelog V8.26 incomplet: ${marker}`);
const v828=read('v828-revision-clean.js');for(const marker of ["const V='8.28'","if(id!=='v81Hub')$('v81Hub')?.classList.add('hidden')",'v828PreToggle','v828SearchToggle','v828GoalToggle','IFSI_V828'])assert(v828.includes(marker),`Correctif V8.28 incomplet: ${marker}`);
const v828Change=read('v828-changelog.js');for(const marker of ['v828Change','V8.28 — Centre de révision simplifié',"badge.textContent='V8.28'"])assert(v828Change.includes(marker),`Changelog V8.28 incomplet: ${marker}`);
for(let i=1;i<=20;i++){const p=`assets/locomotor/locomotor-${String(i).padStart(2,'0')}.webp`;assert(fs.existsSync(p),`Planche locomoteur locale absente: ${p}`)}
const v829=read('v829-locomotor-atlas.js');for(const marker of ["const V='8.30.2'",'const ATLAS=[','loco_atlas_01','loco_atlas_20','buildCatalogSection','data-v830open','v830ZoomOpen','setFav','Consultation + zoom','👁️ Voir la planche','assets/locomotor/locomotor-','IFSI_V830'])assert(v829.includes(marker),`Atlas locomoteur V8.30.2 incomplet: ${marker}`);assert(!v829.includes('id="v830Train"')&&!v829.includes('id="v830Test"')&&!v829.includes('function renderTrain(')&&!v829.includes('function renderTest('),'Les modes locomoteur entraînement/test doivent rester désactivés');const locoCount=(v829.match(/id:'loco_atlas_/g)||[]).length;assert(locoCount===20,`Atlas locomoteur incomplet: ${locoCount}/20 planches`);
const v829Change=read('v829-changelog.js');for(const marker of ['v829Change','V8.29 — Atlas anatomique locomoteur HD',"badge.textContent='V8.29'"])assert(v829Change.includes(marker),`Changelog V8.29 incomplet: ${marker}`);
const v830Change=read('v830-changelog.js');for(const marker of ['v830Change','V8.30 — Anatomie locomotrice active et mises à jour robustes',"badge.textContent='V8.30'"])assert(v830Change.includes(marker),`Changelog V8.30 incomplet: ${marker}`);
const v8301Change=read('v8301-changelog.js');for(const marker of ['v8301Change','V8.30.1 — Correctif mobile atlas locomoteur',"badge.textContent='V8.30.1'"])assert(v8301Change.includes(marker),`Changelog V8.30.1 incomplet: ${marker}`);
const v8302Change=read('v8302-changelog.js');for(const marker of ['v8302Change','V8.30.2 — Locomoteur en consultation stable',"badge.textContent='V8.30.2'"])assert(v8302Change.includes(marker),`Changelog V8.30.2 incomplet: ${marker}`);
const analytics=read('analytics-v77.js');
for(const marker of ["const VERSION='7.7'",'analytics_events','app_open','qcm_start','qcm_finish','resource_open','vocal_start','ifsiabc_analytics_optout_v1','sessionStorage','IFSI_V77'])assert(analytics.includes(marker),`Analytics V7.7 incomplet: ${marker}`);
assert(analytics.includes('sb_publishable_'),'Clé publishable Supabase absente');assert(!analytics.includes('sb_secret_'),'Une clé secrète ne doit jamais être exposée côté client');
for(const forbidden of ['email_address:','full_name:','username:','user_id:','ip_address:'])assert(!analytics.includes(forbidden),`Champ personnel interdit dans analytics: ${forbidden}`);
assert(analytics.includes("$('v77Privacy')?.remove()"),'Le bloc statistiques doit être retiré de l’accueil');assert(!analytics.includes("host.appendChild(box)"),'Le bloc statistiques ne doit plus être injecté sur l’accueil');
const v79=read('v79-themes.js');for(const marker of ["const VERSION='7.9'",'v79Builder','themeOf','difficultyOf','startCustom','IFSI_V79'])assert(v79.includes(marker),`Fonction V7.9 absente: ${marker}`);
const v74=read('v74-pack.js');for(const marker of ['v74-domain-group','v74-domain-body','domainName74','Ressources rangées par domaine puis par UE.'])assert(v74.includes(marker),`Rangement Mes cours V8.10 incomplet: ${marker}`);
const calc=read('calculs-parcours-v1.js');for(const marker of ["COURSE_ID='calculs_doses_mathematiques'",'stageFor','startProgressive','IFSI_CALCULS'])assert(calc.includes(marker),`Parcours calculs incomplet: ${marker}`);
const v81=read('v81-suite.js');for(const marker of ["const V='8.1'",'v81_activity','v81_goal','Bilan détaillé','Points faibles','Examen blanc intelligent','Avant partiel','Recherche avancée','startWeak','startMock','startQuick','startPreExam','IFSI_V81'])assert(v81.includes(marker),`Fonction V8.1 absente: ${marker}`);for(const marker of ['qcm_start','selected_courses','themes','mode','count'])assert(v81.includes(marker),`Analytics V8.1 incomplète: ${marker}`);
const v82=read('v82-nav-anatomy.js');for(const marker of ["const V='8.24'",'showSystemBoards','URINARY_BOARDS','urinary001','urinary002','urinary003','systeme_urinaire','systeme_cardiovasculaire','Anatomie & Physiologie','Des planches anatomiques classées par cours.','Voir les planches','v82-resp-card','index:1','Apprendre','S’entraîner','Tester','data-v82diagram','systeme_respiratoire','showAnatomy','IFSI_V82'])assert(v82.includes(marker),`Catalogue Anatomie V8.24 incomplet: ${marker}`);
assert(!v82.includes("return (resources(def.id).infographics||[])"),'Une infographie ne doit jamais devenir automatiquement une planche anatomique');
assert(v82.includes('séparation stricte')&&v82.includes('return []'),'Règle V8.19 de séparation Infographies / Anatomie absente');
const v83=read('v83-anatomy-interactive.js');for(const marker of ["const V='8.12'",'SYSTEM_META','systeme_urinaire','urinary001','urinary002','urinary003','1oMT0A4FuqrVWaI8GDLIKeI1qc3qxm67V','1GdqA-Vw5zIWBZFzLTLfOrpatl9ayJ57J','155CIVMe4XaPcfkcGM8SS2MFW5XdL7Hpl','v83Zoom','v83ZoomOpen','bindZoom','zoomBy','pointermove','wheel','resp003','resp013','resp015','drive.google.com/thumbnail?id=1_xbRk8WEGKha8Mggn0br5oAFQnxveXtJ','drive.google.com/thumbnail?id=1G2agsVxnMlIeksAdV0-vguUE5bRKQ65Y','drive.google.com/thumbnail?id=11A147V9LowK3-PnJASkqmrfU-T1nTVIJ','resp-official-bronchial-learn.jpg','Support officiel du cours','Apprendre','S’entraîner','Tester','diagramMastery','toggleFavorite','openDiagram','ifsiabc_v83_anatomy_mastery_v1','IFSI_V83'])assert(v83.includes(marker),`Planche interactive V8.12 incomplète: ${marker}`);assert(!v83.includes('schema-resp003.svg')&&!schemaSource.includes('schema-resp003.svg'),'Les SVG respiratoires simplifiés ne doivent plus être actifs');
if(skipped.length)console.warn('⚠️ Packs optionnels ignorés:',skipped.join(' | '));
console.log(`✅ TNR données: ${runtime.length+schemaIds.length} questions runtime contrôlées`);
console.log(`✅ Banque calculs: ${calcQuestions.length} questions exploitables`);
console.log(`✅ ${vocals.length} vocaux et ${registry.courses.length} courseId contrôlés`);
const v84=read('v84-respiratory-polish.js');for(const marker of ["const V='8.11'",'function decorate(){updateBodyClass()}'])assert(v84.includes(marker),`Couche respiratoire V8.11 incomplète: ${marker}`);
const v85=read('v85-home-lite.js');for(const marker of ["const V='8.5'",'v85-home','v82Primary','v76-today','⚙️ Plus','IFSI_V85'])assert(v85.includes(marker),`Accueil V8.5 incomplet: ${marker}`);
const v86=read('v86-home-clean.js');for(const marker of ["const V=window.IFSI_APP_VERSION||'8.30.2'",'v86-home','v86Tools','v86SettingsDialog',"$('v76More')?.remove()",'IFSI_V86'])assert(v86.includes(marker),`Accueil V8.30 incomplet: ${marker}`);
const v87=read('v87-settings.js');for(const marker of ["const V=window.IFSI_APP_VERSION||'8.30.2'",'settings87','v87Nav','Exporter mes résultats','Sauvegarde complète','Statistiques anonymes','Journal des versions','v87ForceUpdate','forceUpdate','v87Server','v87Build','IFSI_V87'])assert(v87.includes(marker),`Paramètres V8.30 incomplets: ${marker}`);
const v813=read('v813-home-discovery.js');for(const marker of ["const V='8.26'",'Rechercher un cours','grid-template-columns:1fr!important','v813Search','v813Results','systeme_urinaire','systeme_respiratoire','systeme_endocrinien','systeme_immunitaire','IFSI_V813'])assert(v813.includes(marker),`Accueil V8.25 incomplet: ${marker}`);assert(!v813.includes('id="v813News"')&&!v813.includes('class="v813-news"'),'Le panneau Nouveautés latéral ne doit plus être rendu sur l’accueil');
const v814=read('v814-respiratory-atlas.js');for(const marker of ["const V='8.14.1'",'resp_atlas_01','resp_atlas_08','Planche ${d.n}/8','DIRECT','1KRBSiliS28bwxYuOVRONNyX--EIFu1Kx','1r7yE3tfybb3NwHTFL7Czc4YU66ovceh4','10MHUvCdXBMzN4NSByaqv_4s_jSa8MnQV','1WlQUhCDtZIsPr-h3atnYxybO0hkYMxlw','1SDHGvwcbP7fdsFZk_ljdeKxwIbGeeRSr','1NlKD6v4iFgbXsnwpJS1IT4fBeqoz4Sl7','1tUgY_VkNhKJcIoFIsu3ZV8jt4LASXyB-','v814Zoom','decorateCatalog','IFSI_V814'])assert(v814.includes(marker),`Atlas respiratoire V8.14.1 incomplet: ${marker}`);assert(!v814.includes("const COLLAGE="),'Le découpage du collage ne doit plus être utilisé');
const v815=read('v815-urinary-atlas.js');for(const marker of ["const V='8.15.1'",'urinary_atlas_01','urinary_atlas_08','Complément anatomie','1xKV0-_DCk9nQbQjcCqibrQILNU9be8fG','v815Zoom','decorateCatalog','IFSI_V815'])assert(v815.includes(marker),`Atlas urinaire V8.15.1 incomplet: ${marker}`);
const v816=read('v816-endocrine-atlas.js');for(const marker of ["const V='8.16'",'endo_atlas_01','endo_atlas_08','Système endocrinien — Vue d’ensemble','Hypothalamus & hypophyse','Thyroïde','Parathyroïdes','Glandes surrénales','Pancréas endocrine','Gonades','Glande pinéale','Complément anatomie','v816Zoom','data-v816toggle','Masquer','Voir les planches','buildCatalogSection','IFSI_V816'])assert(v816.includes(marker),`Atlas endocrinien V8.16 incomplet: ${marker}`);
const v821=read('v821-resource-audit.js');for(const marker of ["const V='8.27'",'Audit catalogue ↔ inventaire Drive','resource-audit-v821.json','IFSI_V823','IFSI_V824','duplicate','anatomyInfoOverlap','runAudit','IFSI_V821'])assert(v821.includes(marker),`Audit ressources V8.27 incomplet: ${marker}`);
const audit821=json('resource-audit-v821.json');assert(audit821.version==='8.27','Snapshot ressources V8.27 invalide');assert(audit821.expectedTotals?.courses===40,'Snapshot V8.27 cours invalide');assert(audit821.expectedTotals?.sheets===47,'Snapshot V8.27 fiches invalide');assert(audit821.expectedTotals?.infographics===138,'Snapshot V8.27 infographies invalide');assert(audit821.expectedTotals?.hdAtlasBoards===80,'Snapshot V8.27 planches HD invalide');assert(Object.keys(audit821.anatomyFolderContracts||{}).length===8,'Snapshot V8.27 dossiers 06 incomplet');
const v817=read('v817-immune-atlas.js');for(const marker of ["const V='8.17'",'immu_atlas_01','immu_atlas_08','Système immunitaire — Vue d’ensemble','Moelle osseuse','Thymus','Réseau lymphatique','Ganglion lymphatique','Rate','Amygdales','Tissus lymphoïdes des muqueuses','Complément anatomie','v817Zoom','data-v817toggle','Masquer','Voir les planches','buildCatalogSection','IFSI_V817'])assert(v817.includes(marker),`Atlas immunitaire V8.17 incomplet: ${marker}`);
const v823=read('v823-cardiovascular-atlas.js');for(const marker of ["const V='8.23'",'cardio_atlas_01','cardio_atlas_08','systeme_cardiovasculaire','Cœur — Situation anatomique','Cœur — Vue antérieure','Cœur — Vue postérieure','Cœur — Vue intérieure','Vascularisation coronaire — Vue antérieure','Vascularisation coronaire — Vue postérieure','Système artériel du corps','Système veineux du corps','v823Zoom','data-v823toggle','Masquer','Voir les planches','IFSI_V823'])assert(v823.includes(marker),`Atlas cardiovasculaire V8.23 incomplet: ${marker}`);assert((v823.match(/id:'cardio_atlas_/g)||[]).length===8,'Atlas cardiovasculaire V8.23 doit contenir 8 planches');
const v824=read('v824-digestive-atlas.js');for(const marker of ["const V='8.24'",'digest_atlas_01','digest_atlas_12','systeme_digestif','Organes du système digestif','Cavité buccale, pharynx et œsophage','Estomac','Péritoine','Aorte abdominale','Vascularisation des viscères','Dents','Division segmentaire du foie','Neuf régions de l’abdomen','Muscles de la paroi abdominale','v824Zoom','data-v824toggle','Masquer','Voir les planches','IFSI_V824'])assert(v824.includes(marker),`Atlas digestif V8.24 incomplet: ${marker}`);assert((v824.match(/id:'digest_atlas_/g)||[]).length===12,'Atlas digestif V8.24 doit contenir 12 planches');
const v822=read('v822-nervous-atlas.js');for(const marker of ["const V='8.22'",'nerv_atlas_01','nerv_atlas_07','nerv_atlas_08','systeme_nerveux','Système nerveux — Vue d’ensemble','Encéphale humain','Lobes cérébraux','Tronc cérébral','Cervelet','Moelle épinière','Nerfs crâniens','Plexus nerveux','v822Zoom','data-v822toggle','Masquer','Voir les planches','IFSI_V822'])assert(v822.includes(marker),`Atlas nerveux V8.22 incomplet: ${marker}`);assert((v822.match(/id:'nerv_atlas_/g)||[]).length===8,'Atlas nerveux V8.22 doit contenir 8 planches');
console.log('✅ V8.30.2 contrôlée : locomoteur en consultation HD stable, hors ligne et zoomable');
console.log('✅ V8.24 contrôlée : système digestif et atlas HD 12 planches');
console.log('✅ V8.23 conservée : système cardiovasculaire, 53 QCM, fiche et atlas HD 8 planches');
console.log('✅ V8.22 conservée : atlas nerveux 8 planches, zoom, favoris et Voir/Masquer');
console.log('✅ V8.21 conservée : audit automatique Drive ↔ Application actif');
console.log('✅ V8.20 conservée : 21 QCM PDF représentés et infographies Drive synchronisées');
console.log('✅ V8.19.1 conservée : accueil sans panneau Nouveautés latéral et statistiques uniquement dans Paramètres');
console.log('✅ V8.19 conservée : séparation Infographies / Anatomie et boutons Masquer');
console.log('✅ V8.18 conservée : système nerveux, 49 QCM et 4 infographies');
console.log('✅ V8.17 conservée : atlas immunitaire HD 8 planches, zoom et favoris');
console.log('✅ V8.16 conservée : atlas endocrinien HD 8 planches, zoom et favoris');
console.log('✅ V8.15.1 contrôlée : atlas urinaire corrigé, planche urètre complète et zoom');
console.log('✅ V8.6 conservée : accueil minimal');
console.log('✅ V8.5 conservée comme couche de compatibilité');
console.log('✅ Visionneuse anatomique multi-systèmes contrôlée : Apprendre, zoom, favoris et progression');
console.log('✅ Anatomie V8.12 contrôlée : catalogue de planches par cours et visionneuse multi-systèmes');
console.log('✅ V8.1 conservée : dashboard, bilan QCM, points faibles, examens, avant-partiel, objectifs, recherche et nouveautés');
console.log('✅ V8.0 calculs conservée avec progression par difficulté');
console.log('✅ Analytics anonymes contrôlées sans clé secrète');