import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(p,'utf8');
const meta=JSON.parse(read('build-meta.json'));
const parts=v=>v.split('.').map(Number);const atLeast=(v,min)=>{const a=parts(v),b=parts(min);for(let i=0;i<Math.max(a.length,b.length);i++){const x=a[i]||0,y=b[i]||0;if(x!==y)return x>y}return true};
assert.ok(atLeast(meta.version,'8.30.39'),'La release courante ne doit pas être antérieure à V8.30.39');
assert.ok(Number(meta.build)>=8339,'Le build courant ne doit pas être antérieur à 8339');
const ui=read('v8339-ui-polish.js');
for(const token of ["const V='8.30.39'","body.v72-dark #v81Body .fc-revision-entry","background:#fff!important","v8339VocalsCard","Vocaux disponibles","v8312Vocals","IFSI_V8339_UI"])assert.ok(ui.includes(token),`Correctif UI incomplet: ${token}`);
const index=read('index.html'),sw=read('sw.js');
assert.ok(index.includes(`./v8339-ui-polish.js?v=${meta.build}`),'Correctif UI absent de index.html');
assert.ok(index.includes(`./v8339-changelog.js?v=${meta.build}`),'Changelog V8.30.39 absent de index.html');
assert.ok(sw.includes("'./v8339-ui-polish.js'"),'Correctif UI absent du cache PWA');
assert.ok(sw.includes("'./v8339-changelog.js'"),'Changelog V8.30.39 absent du cache PWA');
console.log('✅ V8.30.39 : flashcards sombres, bouton blanc et vocaux hors objectifs contrôlés');
